# Site settings
title: ownCluster
author: "Jörn Friedrich Dreyer"
#tagline: Notes on scaling web applications on a banana pi cluster.
email: jfd+owncluster@butonic.de
description: > # this means to ignore newlines until "baseurl:"
  Notes on scaling web applications on a banana pi cluster.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://owncluster.de" # the base hostname & protocol for your site
paginate: 1

twitter_username: butonic
github_username:  owncluster


style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/owncluster/"
  - twitter: "https://twitter.com/butonic/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Serve settings
host: 192.168.1.105

# Outputting
permalink: /:year/:month/:day/:title

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
